# Generated by Django 3.1.4 on 2020-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Last Name')),
                ('attached_file', models.FileField(upload_to='CVs', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
            },
        ),
    ]
